# Generated by Django 4.0.5 on 2022-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='contet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
