# Generated by Django 4.0.5 on 2022-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mypost_comment_alter_mypost_contet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
