# Generated by Django 4.0.5 on 2022-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_mypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='comment',
        ),
        migrations.AlterField(
            model_name='mypost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mypost',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
