# Generated by Django 4.0.5 on 2022-06-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_mypost_comment_alter_mypost_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, default='media/defult.jpg', null=True, upload_to=''),
        ),
    ]
