# Generated by Django 4.0.5 on 2022-06-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='user_likes',
            field=models.ManyToManyField(related_name='userlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='blog.mypost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mypost',
            name='likes',
        ),
        migrations.AddField(
            model_name='mypost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
