# Generated by Django 4.0.5 on 2022-06-19 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_mypost_user_likes_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='user_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='userlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
